server:
  port: 8080
spring:
  application:
    name: health-club
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
