spring:
  profiles:
    active: "dev"

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/healthclub
    username: root
    password: password
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  logging:
    level:
      ROOT: INFO

---
spring:
  config:
    activate:
      on-profile: prod
